runtime: python27
threadsafe: true
version: 2

handlers:

- url: /edit/.*
  script: edit.application
  login: required
- url: /static
  static_dir: static
- url: /construction
  script: construction.application
  login: admin
- url: .*
  script: main.application


libraries:
- name: webapp2
  version: "2.5.2"
- name: jinja2
  version: "2.6"
- name: markupsafe
  version: "0.15"
- name: PIL
  version: latest

builtins:
- deferred: on
